collision_spheres:
  fr3_link0:
  - center:
    - 0.0
    - 0.0
    - 0.085
    radius: 0.03
  - center:
    - -0.1
    - -0.0
    - 0.085
    radius: 0.03
  fr3_link1:
  - center:
    - 0.0
    - -0.08
    - 0.0
    radius: 0.055
  - center:
    - 0.0
    - -0.03
    - 0.0
    radius: 0.06
  - center:
    - 0.0
    - 0.0
    - -0.12
    radius: 0.06
  - center:
    - 0.0
    - 0.0
    - -0.17
    radius: 0.06
  fr3_link2:
  - center:
    - 0.0
    - 0.0
    - 0.03
    radius: 0.055
  - center:
    - 0.0
    - 0.0
    - 0.08
    radius: 0.055
  - center:
    - 0.0
    - -0.12
    - 0.0
    radius: 0.055
  - center:
    - 0.0
    - -0.17
    - 0.0
    radius: 0.055
  fr3_link3:
  - center:
    - 0.0
    - 0.0
    - -0.06
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - -0.1
    radius: 0.06
  - center:
    - 0.08
    - 0.06
    - 0.0
    radius: 0.052
  - center:
    - 0.08
    - 0.02
    - 0.0
    radius: 0.052
  fr3_link4:
  - center:
    - 0.0
    - 0.0
    - 0.02
    radius: 0.052
  - center:
    - 0.0
    - 0.0
    - 0.06
    radius: 0.052
  - center:
    - -0.08
    - 0.095
    - 0.0
    radius: 0.055
  - center:
    - -0.08
    - 0.06
    - 0.0
    radius: 0.052
  fr3_link5:
  - center:
    - 0.0
    - 0.03
    - 0.0
    radius: 0.05
  - center:
    - 0.0
    - 0.082
    - 0.0
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - -0.22
    radius: 0.05
  - center:
    - 0.0
    - 0.052
    - -0.18
    radius: 0.04
  - center:
    - 0.01
    - 0.08
    - -0.14
    radius: 0.022
  - center:
    - 0.01
    - 0.085
    - -0.11
    radius: 0.022
  - center:
    - 0.01
    - 0.09
    - -0.08
    radius: 0.022
  - center:
    - 0.01
    - 0.095
    - -0.05
    radius: 0.022
  - center:
    - -0.01
    - 0.08
    - -0.14
    radius: 0.022
  - center:
    - -0.01
    - 0.085
    - -0.11
    radius: 0.022
  - center:
    - -0.01
    - 0.09
    - -0.08
    radius: 0.022
  - center:
    - -0.01
    - 0.095
    - -0.05
    radius: 0.022
  - center:
    - 0.0
    - -0.009
    - 0.0
    radius: 0.05
  fr3_link6:
  - center:
    - 0.085
    - 0.035
    - 0.0
    radius: 0.045
  - center:
    - 0.085
    - 0.0
    - 0.0
    radius: 0.045
  - center:
    - 0.085
    - -0.015
    - 0.0
    radius: 0.045
  fr3_link7:
  - center:
    - 0.0
    - 0.0
    - 0.07
    radius: 0.045
  - center:
    - 0.02
    - 0.04
    - 0.08
    radius: 0.024
  - center:
    - 0.04
    - 0.02
    - 0.08
    radius: 0.024
  - center:
    - 0.04
    - 0.06
    - 0.085
    radius: 0.02
  - center:
    - 0.06
    - 0.04
    - 0.085
    radius: 0.02
  base_link:
  - center:
    - 0.028
    - -0.009
    - -0.125
    radius: 0.01929
  - center:
    - -0.006
    - 0.009
    - -0.042
    radius: 0.01929
  - center:
    - -0.001
    - -0.008
    - -0.019
    radius: 0.01929
  - center:
    - 0.004
    - -0.011
    - -0.064
    radius: 0.01929
  - center:
    - -0.022
    - 0.008
    - -0.07
    radius: 0.01929
  - center:
    - -0.027
    - -0.012
    - -0.124
    radius: 0.01929
  - center:
    - 0.023
    - -0.009
    - -0.098
    radius: 0.01929
  - center:
    - -0.0
    - -0.007
    - -0.126
    radius: 0.01929
  - center:
    - -0.002
    - -0.005
    - -0.039
    radius: 0.01929
  - center:
    - -0.0
    - -0.01
    - -0.098
    radius: 0.01929
  - center:
    - -0.024
    - -0.011
    - -0.098
    radius: 0.01929
  - center:
    - 0.023
    - -0.004
    - -0.068
    radius: 0.01929
  right_index_1:
  - center:
    - -0.001
    - 0.027
    - -0.007
    radius: 0.00887
  - center:
    - -0.006
    - 0.011
    - -0.007
    radius: 0.00887
  - center:
    - -0.006
    - -0.002
    - -0.007
    radius: 0.00887
  right_index_2:
  - center:
    - 0.002
    - 0.014
    - -0.006
    radius: 0.01022
  - center:
    - 0.001
    - 0.03
    - -0.006
    radius: 0.00918
  - center:
    - -0.005
    - 0.045
    - -0.006
    radius: 0.00866
  right_little_1:
  - center:
    - -0.007
    - -0.003
    - -0.007
    radius: 0.00888
  - center:
    - -0.007
    - 0.013
    - -0.007
    radius: 0.00888
  - center:
    - -0.004
    - 0.026
    - -0.007
    radius: 0.00888
  right_little_2:
  - center:
    - 0.01
    - -0.006
    - -0.006
    radius: 0.00924
  - center:
    - 0.024
    - -0.005
    - -0.006
    radius: 0.00924
  - center:
    - 0.036
    - -0.003
    - -0.006
    radius: 0.00837
  right_middle_1:
  - center:
    - -0.006
    - 0.011
    - -0.008
    radius: 0.00887
  - center:
    - -0.007
    - -0.002
    - -0.006
    radius: 0.00887
  - center:
    - -0.002
    - 0.027
    - -0.007
    radius: 0.00887
  right_middle_2:
  - center:
    - 0.002
    - 0.015
    - -0.006
    radius: 0.01053
  - center:
    - 0.002
    - 0.033
    - -0.006
    radius: 0.00944
  - center:
    - -0.005
    - 0.049
    - -0.006
    radius: 0.0089
  right_ring_1:
  - center:
    - -0.006
    - -0.002
    - -0.007
    radius: 0.00987
  - center:
    - -0.003
    - 0.026
    - -0.007
    radius: 0.00987
  - center:
    - -0.005
    - 0.014
    - -0.007
    radius: 0.00987
  right_ring_2:
  - center:
    - 0.003
    - 0.016
    - -0.006
    radius: 0.01021
  - center:
    - 0.001
    - 0.031
    - -0.006
    radius: 0.00917
  - center:
    - -0.004
    - 0.045
    - -0.006
    radius: 0.00866
  right_thumb_1:
  - center:
    - 0.0
    - 0.0
    - 0.0
    radius: 0.005
  right_thumb_2:
  - center:
    - 0.019
    - 0.014
    - -0.012
    radius: 0.016
  - center:
    - 0.007
    - 0.009
    - -0.013
    radius: 0.016
  right_thumb_3:
  - center:
    - 0.005
    - -0.001
    - -0.005
    radius: 0.00974
  - center:
    - 0.015
    - 0.005
    - -0.006
    radius: 0.00974
  right_thumb_4:
  - center:
    - 0.025
    - 0.014
    - -0.007
    radius: 0.01013
  - center:
    - 0.012
    - 0.002
    - -0.007
    radius: 0.00934
